### ISSUE TITLE
[tree] Create NuGet parser

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/spdx-builder#83]
Add support for NuGet parser.

**Comment by Brend-Smits** [comment]
Before being able to support a NuGet parser, there needs to be something to parse that is directly from the source. There is the ``dotnet list package --include-transitive`` command which outputs a list of packages... The problem is that this is very difficult to compute for machines. Refer to the issue on the NuGet repository for more information. https://github.com/NuGet/Home/issues/7752 Seems like there is very little activity on this issue. This is what we need to easily support NuGet directly. I will be looking at workarounds for the time being. More information will be added later.
